[package]
name = "gst-log-parser"
version = "0.1.0"
authors = ["Guillaume Desmottes <guillaume@desmottes.be>"]

[dependencies]
itertools = "0.5.9"
gstreamer = "0.9.1"
regex = "0.2"
lazy_static = "0.2.9"
structopt = "0.1.5"
structopt-derive = "0.1.5"
